name=robo_hardware
version=1.0.0
author=Grupo de robotica do IFRN-CM
maintainer=Grupo de robotica do IFRN-CM <lennedy.soares@ifrn.edu.br>
sentence=Biblioteca para os robos desenvolvidos pelo grupo de robotica do IFRN-CM.
paragraph=Biblioteca para os robos desenvolvidos pelo grupo de robotica do IFRN-CM.
category=Device Control
url=https://github.com/IFRN-robotica-CM/robo_hardware
architectures=*
depends=Adafruit BusIO
